# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sagami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pdx214 pdx215 pdx217,$(TARGET_DEVICE)),)

endif
