# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sagami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter perf,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
